name: Build release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build release
      id: build-release
      uses: Joshua-Ashton/arch-mingw-github-action@v7
      with:
        command: |
          export VERSION_NAME="2.6"
          ./package-release.sh ${VERSION_NAME} build --no-package
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
          mv build/vkd3d-proton-${VERSION_NAME} vkd3d-proton-${VERSION_NAME}
          tar zcvf vkd3d-proton-${VERSION_NAME}.tar.gz vkd3d-proton-${VERSION_NAME}
          
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: false
        prerelease: false
        automatic_release_tag: "vkd3d-proton-${{ env.VERSION_NAME }}"
        title: "vkd3d-proton-${{ env.VERSION_NAME }}"
        files: "vkd3d-proton-${{ env.VERSION_NAME }}.tar.gz"
